//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HieuThuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public long ID { get; set; }
        public int Quantity { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<decimal> Totalprice { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Order Order { get; set; }
    }
}
